### ISSUE TITLE
16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26

### ISSUE THREAD

**Issue by samuelhieber** [cornwarecjp/Bitcoin-Cash-Off-The-Grid#1]
I have tried to generate a raw transaction with this tool and broadcast it. When boadcasting it to the blockdozer the following message popped-up: 
"16: mandatory-script-verify-flag-failed (Signature must be zero for failed CHECK(MULTI)SIG operation). Code:-26"
The transaction was not multi-sig. Is there something I need to change? 
Thank you very much for your help. 

Kind regards,

**Comment by samuelhieber** [comment]
found the issue

**Comment by cornwarecjp** [comment]
What was the source of the issue? What did you do to fix it? Please provide answers to these questions here: that might help other people who encounter the same problem.

**Comment by dennischiume** [comment]
Please assist
